### ISSUE TITLE
BUG : Favicon should be added !! 

### ISSUE THREAD

**Issue by prashh-k** [EternoSeeker/Slot-Machine#1]
Favicon should be added for a web page.

**Expected Behavior: **
The favicon should be added like this, 
![after_favicon](https://github.com/EternoSeeker/Slot-Machine/assets/104455228/ea250cc8-df8d-4b15-907f-09fafec0daf6)

**Actual Behavior: **
The favicon is not added, 
![before_favicon](https://github.com/EternoSeeker/Slot-Machine/assets/104455228/ff472e9f-5cae-4a73-8158-d51ca6076ec9)

**Comment by Deepakktripathy** [comment]
Hey, I would like to work on this issue

**Comment by prashh-k** [comment]
I have fixed this issue. 
Now add please add a Hacktobarfest label to this issue and my pull request also,

**Comment by prashh-k** [comment]
@Deepakktripathy what is this bro why are linking your pull request with issue ?
