### ISSUE TITLE
Feature: Adding Footer and Navigation Bar

### ISSUE THREAD

**Issue by Ananyaa03** [EternoSeeker/Slot-Machine#11]
I would like to add a nav bar and footer.

**Comment by Ananyaa03** [comment]
Can you assign this issue to me under hacktoberfest23?

**Comment by EternoSeeker** [comment]
Please give more details about the contents of the nav bar and footer, and you can start working on it

**Comment by Ananyaa03** [comment]
The navbar will include:
1. Home , Contact Us , about us , login links
2. And footer will contain the social media profiles and copyright

**Comment by EternoSeeker** [comment]
Alright, you can work on the PR now
