### ISSUE TITLE
Add "Scroll to Top" button in Readme.md

### ISSUE THREAD

**Issue by Pooja11kumari** [EternoSeeker/Slot-Machine#16]
**Description**
Add the "Scroll to top" button in the Readme.md file.Which will act as a automatic scroller when clicked.And scrolls to the TOP of the File in just one click.

**Comment by Pooja11kumari** [comment]
@EternoSeeker I would like to add this feature in your Readme.md file.Can i work on it?

**Comment by EternoSeeker** [comment]
yes you can.
