### ISSUE TITLE
Bug : Fixed the spin button icon

### ISSUE THREAD

**Issue by prashh-k** [EternoSeeker/Slot-Machine#4]
The icon in spin button is not visible 

**Expected Behavior :**
The Icon should be visible in spin button like this, 
![after_spin](https://github.com/EternoSeeker/Slot-Machine/assets/104455228/15dc57c0-cd0e-4f1a-a4e0-71deff7b2163)

**Actual Behavior :**
The Icon is not visible, 
![before_spin](https://github.com/EternoSeeker/Slot-Machine/assets/104455228/03297b79-71fb-4382-a0ec-86179d9f8a30)

**Comment by EternoSeeker** [comment]
The issue existed because I didn't notice that the file wasn't uploaded in the images folder, was fixed
