### ISSUE TITLE
Adding slot machine background to make it more user appealing

### ISSUE THREAD

**Issue by Sameersawant77** [EternoSeeker/Slot-Machine#6]
https://img.freepik.com/premium-photo/luck-success-casino-when-playing-casino-slot-machine_124507-54652.jpg

**Comment by EternoSeeker** [comment]
Do you have some more options for the images ?, also we'll need to reduce image's opacity if we consider adding it

**Comment by Sameersawant77** [comment]
@EternoSeeker you can provide me an image whichever you like, I will reduce the opacity and apply the background ^^

**Comment by EternoSeeker** [comment]
https://www.freepik.com/free-ai-image/spinning-roulette-wheel-brings-vibrant-nightlife-fun-generative-ai_42212821.htm#page=2&query=slot%20machine%20background&position=5&from_view=search&track=ais

**Comment by EternoSeeker** [comment]
Sorry for using the term opacity, I meant the brightness of the image shall be reduced and the text should be made white for it to look readable
